name: Build SunamoStringReplace

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringReplace
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringReplace/SunamoStringReplace.csproj

    - name: Build
      run: dotnet build SunamoStringReplace/SunamoStringReplace.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringReplace.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringReplace.Tests/SunamoStringReplace.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringReplace.Tests/SunamoStringReplace.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringReplace.Tests/SunamoStringReplace.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
